### ISSUE TITLE
Different folder structure for crawler repo

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#11]
The current folder structure is a little bit confusing and not reflective of the purpose of the crawler repo.
As far as I understood, the whole repo is for all the web crawlers we will have (facebook API, other APIs)

For now the [README](https://github.com/WorldBrain/crawler/blob/master/README.md) of the crawler works because there is only one crawler. (so we dont have to change that) 
Are the files in the repo toplevel something that is for the article-crawler?
What will be the content of the crawler/crawler folder then?

Furthermore we should rename the repo in some way. crawler could be a little misleading. 
**Suggestions:**
 - Content_Aggregator
 - Aggregator 
 - Content_Collector

And the subfolder /crawler should be called a little bit more along the lines of what it does. 
**Suggestion:**
 - /index_domain
 - /domain_indexer
 - /domain2articles
 - /article_crawler

@lwm @arsenal9971

**Comment by lwm** [comment]
Actually, I think this repo needs to become the server logic repo. I think we will need to all sync on this.

**Comment by oliversauter** [comment]
ok, and where do we put the crawler part then?
will this be part of the server logic? What do you consider as server logic?

**Comment by lwm** [comment]
> will this be part of the server logic?

Yes, that is it. The server will receive a request and then call the crawler. 

The crawlers will all be in a sub directory, I suppose.

> What do you consider as server logic?

https://www.djangoproject.com/start/overview/

The flow would be:

```
Input: client -> django -> crawler
```

**Comment by oliversauter** [comment]
> EDIT: Let's wait until Monday to arrange this? We can still work on getting a working crawler.

Sounds good!

> The crawlers will all be in a sub directory, I suppose.

What is a subrepo? just another one?

**Comment by lwm** [comment]
> EDIT: Let's wait until Monday to arrange this? We can still work on getting a working crawler.
Sounds good!

:+1: 

> What is a subrepo? just another one?

Yep, a directory inside another directory.

**Comment by lwm** [comment]
Closing this for now. The whole structure is going to change in the next day as the server merges.
