### ISSUE TITLE
Unable to add new source to db

### ISSUE THREAD

**Issue by dev-tim** [WorldBrain/cortex#18]
When I was trying to add new source to the django app, I got an exception:

```
TypeError at /api/sources/
Got a `TypeError` when calling `Source.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Source.objects.create()`. You may need to make the field read-only, or override the SourceSerializer.create() method to handle this correctly.
Original exception text was: 'processed_linkchecker' is an invalid keyword argument for this function.
```

I'm trying to investigate it, and learn django, but having some issues. 
@tobisanya @hoshomoh  Can you help? 

Also I had a question how I would handle GET or POST requests on the app side? Should I add some django specific code? 

Let's make a call to find better solution.

**Comment by hoshomoh** [comment]
@dev-tim I would take a look at this today. And yes feel free to add some Django-specific code.
Let's chat on gitter. I need to know how you are consuming the API

**Comment by zartdev** [comment]
Hm, it was some Django issue, I'll take a look into that. Something is wrong with serializer.

**Comment by oliversauter** [comment]
Any updates on that @hoshomoh?

**Comment by hoshomoh** [comment]
My next PR should fix that. And more importantly we need to decide on the API documentation strategy as suggested by @dev-tim [here](https://github.com/WorldBrain/cortex/issues/14)
