### ISSUE TITLE
Setup Django

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#2]

**Comment by oliversauter** [comment]
I am done with the API for source and URLs.
I would write Test and push tomorrow. Let me know if it's cool to push and update with test later so that https://app.asana.com/0/162177489032308/162177489032308 can start work on the SEARCH API

**Comment by oliversauter** [comment]
Yes absolutely fine. https://app.asana.com/0/162185052176345/162185052176345.

**Comment by hoshomoh** [comment]
This should also be closed. Implemented by me.
