### ISSUE TITLE
Architecture: Defining the facebook-crawler pipeline

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#2]
# Working DRAFT

### What data should we save from Facebook's Graph API

More infos here: https://developers.facebook.com/docs/graph-api/reference/v2.6/post/

It seems like this information has to be saved into a graphDB to be fully explorable. 

**Click on link to see Facebook Graph API Explorer settings.**
- Trusted Groups/Pages 
  - [All posts ](https://developers.facebook.com/tools/explorer?method=GET&path=EclecticScience%2Ffeed%3Fsince%3D1136073600&version=v2.6)
     - [Single post data](https://developers.facebook.com/tools/explorer?method=GET&path=738880359476824_1238340652864123%3Ffields%3Dcaption%2Ccreated_time%2Cdescription%2Cfrom%2Clink%2Cmessage%2Cmessage_tags%2Cname%2Cobject_id%2Cpicture%2Cshares%2Csource%2Cto%2Ctype%2Ccomments&version=v2.6)
         - caption
         - created_time
         - description
         - from
         - link
         - message
         - message_tag
         - name
         - picture
         - type
         - picture
         - object_id
         - shares
         - source
         - to
         - child_attachement
         - coordinates
         - is_popular
         - parent_id
         - /reactions
            - id
            - name
            - type
         - permalink_url
         - sharedposts
         - likes
            - id
            - name
         - attachments
         - comments
            - from
            - created_time
            - id
            - message
            - comment_count
            - like_count
            - comments (of comments)
               - from
               - created_time
               - id
               - message
               - comment_count
               - like_count
               - parent

**Comment by lwm** [comment]
Could you explain a little further the use case for crawling facebook?

I doubt science users are going to be submitting a facebook comment as 'trusted' ?

**Comment by dev-tim** [comment]
Agree, use case is quite narrow. @oliversauter could you elaborate on this?

**Comment by oliversauter** [comment]
This issue was just my documentation of a brief research. Is not finished yet, since no priority (web crawler first).
Thats what I tried to indicate with "Working Draft"
The document will be expanded with more info as soon as we tackle this. 

In fact, facebook will be our central information source to evaluate quality, impact and correlation. (at least in the beginning)
Aas an example, we would be able to see if an article has been posted and if another article has been used in a reply comment, this way we already could have some idea of relation. 

> I doubt science users are going to be submitting a facebook comment as 'trusted' ?

Its not that they submit the comment as trusted, but the page or group.
What we would do is crawling every post, comment and their interaction (likes, shares, reactions) **from facebook groups/pages that are often used by the scientific community.** ([Example](https://www.facebook.com/groups/FAFDL/)) The skeptical community/sciCom main place of interaction these days is facebook.  (Commenting, evaluating, debating etc)
I (and other skeptics) actually do my research a lot this way: Typing in the link to a study/news article and oftentimes it already has been dissected in one of the facebook groups by users. 

So regarding the search feature, we would also make it possible to search through all those groups at once, not just websites.

**Comment by lwm** [comment]
> Thats what I tried to indicate with "Working Draft"

Righto, just wanted to get some feedback on it.

It's not really clear still but let's work on it when we have time! :+1:

**Comment by oliversauter** [comment]
Could you explain a little further the use case for crawling facebook?

I doubt science users are going to be submitting a facebook comment as 'trusted' ?

[--- Commented from Asana.com
#commenter Oliver
---[aa]

**Comment by oliversauter** [comment]
Agree, use case is quite narrow. @oliversauter could you elaborate on this?

[--- Commented from Asana.com
#commenter Oliver
---[aa]

**Comment by oliversauter** [comment]
This issue was just my documentation of a brief research. Is not finished yet, since no priority (web crawler first).
Thats what I tried to indicate with "Working Draft"
The document will be expanded with more info as soon as we tackle this. 

In fact, facebook will be our central information source to evaluate quality, impact and correlation. (at least in the beginning)
Aas an example, we would be able to see if an article has been posted and if another article has been used in a reply comment, this way we already could have some idea of relation. 

> I doubt science users are going to be submitting a facebook comment as 'trusted' ?

Its not that they submit the comment as trusted, but the page or group.
What we would do is crawling every post, comment and their interaction (likes, shares, reactions) **from facebook groups/pages that are often used by the scientific community.** ([Example](https://www.facebook.com/groups/FAFDL/)) The skeptical community/sciCom main place of interaction these days is facebook.  (Commenting, evaluating, debating etc)
I (and other skeptics) actually do my research a lot this way: Typing in the link to a study/news article and oftentimes it already has been dissected in one of the facebook groups by users. 

So regarding the search feature, we would also make it possible to search through all those groups at once, not just websites.

[--- Commented from Asana.com
#commenter Oliver
---[aa]
