### ISSUE TITLE
List search results

### ISSUE THREAD

**Issue by zartdev** [WorldBrain/cortex#21]
As client API I should be able to get a list of search results by semantic query. 

Result list should be paginated and support limit/offset functionality.

**Comment by oliversauter** [comment]
@hoshomoh this is also something we talked about and is important to get ready.

#### Open Questions:
1. Can you do this with the current state of the code of the client or is there something still missing?

**Comment by oliversauter** [comment]
@hoshomoh this would also be a great chance for you to have a look into the front end code and understand the connections. 

I assume therefore it makes sense that you take on the task of connecting the client with the django application.

Additionally, the requests via the search bar should be sent as requests to elastic search.
   - when user choses to filter for a domain, limit search request to elastic search to these sources. Hence add this parameter of the sources to request

**Comment by hoshomoh** [comment]
I think this task should be broken down into two. One is to make sure that Elastic search endpoint support pagination and filter as suggested by @zartdev . The other would be the integration of the client with the API which is something I won't mind doing.

For Elastic search, I think @tobisanya is best to take this.

**Comment by oliversauter** [comment]
ok, can you open those 2 tasks and describe them to the best of your knowledge?

**Comment by hoshomoh** [comment]
Okay I would do just that.

**Comment by hoshomoh** [comment]
@tobisanya is already working on the search endpoint. I think this should be closed. And maybe an Integration ticket be created.

**Comment by oliversauter** [comment]
this is done I assume with #37

**Comment by hoshomoh** [comment]
We can say that. But, there is an integration part of this that still needs to be done. It's fine to close this and create a frontend integration ticket for listing search results. Like that anyone can pick it up.

**Comment by oliversauter** [comment]
ok, i think this is already there with: https://github.com/WorldBrain/webmarks/issues/31
