### ISSUE TITLE
Setup Webmarks + cortex on a production environment

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#26]
We need to have everything set up on a production environment (including dockerisation) etc. 

Please @lwm can you add more infromation to this EPIC

**Comment by lwm** [comment]
@oliversauter 

You need to split this into two issues. (rename this one please!)

One that goes in webmarks for their deployment and one for cortex, for its deployment.

I have already listed the first step of this in #22.

> Please @lwm can you add more infromation to this EPIC

Which EPIC? You mean more issues?

**Comment by oliversauter** [comment]
This is why it is an epic. An epic is a rather high level thing to encapsule more than 1 subtask to do. in this case 1 task is setting up webmarks and the other one is setting up cortex

**Comment by lwm** [comment]
> This is why it is an epic. An epic is a rather high level thing to encapsule more than 1 subtask to do. in this case 1 task is setting up webmarks and the other one is setting up cortex

This is the job of zenhub. To draw the big picture.

We already agreed on this in the chat:
```
@oliver
> yeah thats the thing
> those features are so high level that the tasks to do WILL span over both areas
>
@lwm
> So those issues will be linked with the usual #<number> convention
> the feature will have an entry point - like, I want a search bar
> that will start in webmarks
> if it makes it past that, we create an issue in cortex, with a link?
>
@oliver
> ok, that sounds good
```

**Comment by oliversauter** [comment]
yeah, but we have to still link them together. Zenhub does not automatically bundle them. We have to know when a high level task is finished.

They even have the features of epic. Thats what they are for.

**Comment by lwm** [comment]
> yeah, but we have to still link them together.

We can use the usual #<issue> convention like we said above. 

You need to find an abstraction *above* github issues to link the big picture.

It makes no sense to have this issue here or https://github.com/WorldBrain/cortex/issues/2

It's simply confusing.

**Comment by lwm** [comment]
Closing after our discussion. Will be moved into `project-management` repo.
