### ISSUE TITLE
Initial integration with ElasticSearch into Django

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#3]
## Goal:

We need a module that indexes a postgreSQL DB with Elastic-Search.

## Implementation Details:
  - Follow the [documentation guide](https://github.com/WorldBrain/project-management#readme-driven-development-rdd) and first make a pull request with the readme. 
  - Mock database entries (for details, check #50).
  - Index those entries using a `reindex` django command in ES. (help code from https://github.com/WorldBrain/cortex/pull/45.)

**Comment by hoshomoh** [comment]
This issue should be closed. Already Implemented by @tobisanya
