### ISSUE TITLE
Investigate frontera

### ISSUE THREAD

**Issue by lwm** [WorldBrain/cortex#35]
https://frontera.readthedocs.io/en/latest/

Created to be used with `scrapy`. Looks very promising for building crawlers.

https://blog.scrapinghub.com/2015/04/22/frontera-the-brain-behind-the-crawls/

I think we need this. A lot.

**Comment by oliversauter** [comment]
This is freakin awesome! Where do you find all that stuff :)

**Comment by lwm** [comment]
It's unfortunately not ready for much I think ...

Ref https://github.com/scrapinghub/frontera/issues/172, https://github.com/scrapinghub/frontera/issues/173

**Comment by lwm** [comment]
It just isn't ready yet. No python 3 support and quite buggy.

**Comment by oliversauter** [comment]
mhh damn. we also need to think about how we keep domains that we already crawled upup to date. I think for that, sorting out the "category" pages of domains might be helpful, we could recrawl them every now and then, so we don't have to crawl the whole domain again. 
Second option is also attaching to the RSS feeds of pages (which are not available everytime)

Or any other idea how we can detect new articles?

**Comment by sibiryakov** [comment]
Guys, I'm going to fix https://github.com/scrapinghub/frontera/issues/173 tomorrow. This import error was introduced in one of last versions. Regarding Python 3, we will have support for python 3 till the end of august I expect.

**Comment by lwm** [comment]
@sibiryakov Thanks for reaching out! I would still like to use frontera!

Is there somewhere I can help with the python3 port? Or someone has it under control?

**Comment by sibiryakov** [comment]
Yes, the @preetwinder and @redapple, first is our GSoC student, and second is his mentor. This problem is being solved publicly, for example https://github.com/scrapinghub/frontera/pull/168
also this https://github.com/wbolster/happybase/pull/116 is a blocker for HBase support.

**Comment by lwm** [comment]
@sibiryakov Subscribed. Thank you very much!

**Comment by lwm** [comment]
Awaiting mentioned fixes above, `frontera` will be an option once more!

**Comment by sibiryakov** [comment]
@lwm Luke, even more. If you could describe what problem you're going to solve may be I could say how to use frontera the right way and confirm it fits well.

**Comment by lwm** [comment]
@sibiryakov 

We intended to use [scrapy][1] with frontera. In our first iteration, we will simply want to accept a domain and crawl all URLs under that domain. However, as we try to get smarter, we want to filter these URLs (which ones are articles?) and prioritise ones (if the site is too big) and do this in a distributed way.

We'd like to run the crawl jobs from a django app in an asynchronous manner.

We will want to store everything we crawl and be able to perform searches over it.

Also, I saw we can optionally scrape when using fontera. In this way, it would be really nice to just traverse URLs and improve from there. Has that feature landed?

Thoughts?

[1]: http://doc.scrapy.org/en/latest/index.html

**Comment by sibiryakov** [comment]
> We intended to use scrapy with frontera. In our first iteration, we will simply want to accept a domain and crawl all URLs under that domain. However, as we try to get smarter, we want to filter these URLs (which ones are articles?) and prioritise ones (is the site is too big?) and do this in a distributed way.
That should work fine. You'd have to implement a custom crawling strategy and use a distributed backends run mode (with strategy worker).

> We'd like to run the crawl jobs from a django app in an asynchronous manner.
I see it as django app injects seeds in constantly running Frontera service. Do you want to track progress also? This is a tricky problem.

> We will want to store everything we crawl and be able to perform searches over it.
This is possible. Usually people use item pipeline in Scrapy. I recommend to use msgpack for serialization.

> Also, I saw we can optionally scrape when using fontera. In this way, it would be really nice to just traverse URLs and improve from there. Has that feature landed?
Well, yes in spider code you can add any post-processing and store results in requests meta and have them later available in strategy worker and perform prioritization.

> Thoughts?
The trickiest part I think is implementation of job concept. Frontera is designed for efficient download of many domains in parallel. It's relatively easy to inject new seed and make it discover the domain and crawl it, but much harder to abort crawling of some domain if it is already scheduled (that would require redesigning the queue, which is BTW encapsulated well).

**Comment by oliversauter** [comment]
@sibiryakov Thanks for your help on this!

How does frontera handle the following usecase of updating? 

Our goal is to index all articles from a domain, once we have crawled one domain, it will have new articles coming out (probably daily). Is there any way to crawl the page and find the new URLs(articles) without having to crawl the whole domain again?

**Comment by sibiryakov** [comment]
@oliversauter For distributed backends there is no revisiting implemented yet. So, you would need to code a bit to add requests to the queue, when needed revisiting is needed.

Next, there is a per-URL state mechanism. Allowing to check if URL was crawled/not crawled/queued/errored before and can be used to check if URL is new.

The states are cached in memory in strategy worker processes, and periodically flushed to storage. SQLAlchemy and HBase is currently supported as a storage.

Here is the States object interface, used by strategy worker.
http://frontera.readthedocs.io/en/latest/topics/frontier-backends.html#frontera.core.components.States

**Comment by lwm** [comment]
Closing this for now. We're moving the crawler out of this repo, 

Thanks for all the input guys.
