### ISSUE TITLE
Module: content_extractor

### ISSUE THREAD

**Issue by arpitgogia** [WorldBrain/cortex#38]
Goal
-
Extracting the important content bits from the HTML code we saved for each article URL

Input
-
Gets the HTML Code from the column ```html``` for each URL in table ```all_urls``` where column ```processed_content_extractor```=```false```

Output
-
Updates(Saves) the following fields in the ```articles``` table

* ```domain_name```,
* ```url```,
* ```text```,
* ```keywords(list)```,
* ```authors(list)```,
* ```publish_date```,
* ```tags(list)```,
* ```summary```,
* ```links(list)```
* ```parse_time```

Technical Implementation
-
Using [Newspaper3k](https://github.com/codelucas/newspaper) Module to parse the HTML and obtain the required fields. Though it doesn't support raw HTML parsing by default but passing the raw HTML to the ```download``` method of an ```article``` object is a good work around.

*[Original Issue for reference](https://github.com/WorldBrain/crawler/issues/4)*

**Comment by oliversauter** [comment]
Great description! :)

**Comment by arpitgogia** [comment]
I had mentioned in the original issue also, **Newspaper3k is a Python 3** library, their [Python 2 branch](https://github.com/codelucas/newspaper/tree/python-2-head) is deprecated and buggy. @hoshomoh @oliversauter, how do we overcome this?

**Comment by hoshomoh** [comment]
Lets switch to python3.  That should be an issue.  I run virtualenv with python3 on my machine.

**Comment by arpitgogia** [comment]
So basically can I go ahead with this module by carrying out all the commands using ```python3``` and ```pip3```?

**Comment by oliversauter** [comment]
If it works lets use p3.

**Comment by oliversauter** [comment]
This is finished?
