### ISSUE TITLE
API Endpoint so that sources can be added via user-facing client

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#40]
As the user, I will be able to filter for sources, that have not been indexed yet (https://github.com/WorldBrain/webmarks/issues/29)

In this case those entries should be saved in the `domain_list` tables with: `indexed`=`false`, `processed_spider`=`false`, `ready_for_crawling`=`false` and `trusted_source`=`false`

This is important to make the entry of unindexed sources by the user possible as described here: https://github.com/WorldBrain/START-HERE/wiki/Specifications-for-Search-Engine-Prototype#3-when-a-user-wants-to-filter-for-a-source-that-has-not-been-indexed-yet

**Comment by oliversauter** [comment]
so this is already done right? @hoshomoh

**Comment by hoshomoh** [comment]
@oliversauter This is already done. But I need to clarify that ```indexed```, ```processed_spider``` and ```ready_for_crawling``` are not separate fields in the ```sources``` table.  Instead, there is a state field that holds what state a  domain is at every given point because a domain cannot be in multiple state at a time. Correct me if I am wrong. A newly added domain would be in ```PENDING``` meaning it is not ```ready_for_crawling``` and it has not been ```indexed```. ```processed_spider``` and ```indexed``` seems to be the same to me.

From ```PENDING```, there is a check that makes sure that the domain cannot be moved to another state except for ```READY``` i.e ```ready_for_crawling``` or ```REJECTED```. 

Finally, from ```READY``` it can then move to ```CRAWLED``` or ```FAILED```. ```CRAWLED``` meaning it was successfully ```processed_spider``` or ```indexed``` while ```FAILED``` meaning otherwise.

This was first implemented by @lwm and I really think its a good design pattern because this way we can add more state for a domain without having to add multiple fields to the ```sources``` table.

**Comment by oliversauter** [comment]
@hoshomoh can you show me the `sources` table in the code? Is this the same as `domain_list` table?

`processed_spider` and `indexed` are 2 different ones. Former says that we have all the URLs and the HTML and latter is after we have been processing the HTML with the module content_extractor (#38)

 So do I understand it right that there are currently 5 states:
`PENDING` = not ready for crawling and needs review
`REJECTED`=not going to be crawled (but needs to be stored anyway)
`READY` = ready for being crawled (which is then used by @vpolisky 's `spider`)
`CRAWLED` = all URLs and HTML extracted ((here we need to save the last time of crawling, so we know when it is time to recrawl the domain)
`FAILED`= some error happened (is the errorlog saved too?) what happens if only some of the URLs fail? is then the whole domain flagged as failed? Would this hinder that the successfully parsed URLs can be indexed in Elastic search?

I would add 2 other states as well:
`CONTENT_COMPLETE` =content extraction complete and URLs of domain ready for being indexed
`INDEXED` = it is indexed in elastic search 

>This was first implemented by @lwm and I really think its a good design pattern because this way we can add more state for a domain without having to add multiple fields to the sources table.

But how can we then represent multiple dimensions in states? like for example dimension of "indexing" and dimension of "trusted"?

**Comment by hoshomoh** [comment]
Yeah, It's the same as ```domain_list``` table. We could add those two state and last time of crawling as you suggested. I am not sure about a state having multiple dimension. Would do a little research about that. But, I doubt if that would be possible because the essence of state is so they don't have multiple dimensions

**Comment by oliversauter** [comment]
i can imagine that a state **cannot** have multiple dimensions. it is rather the question how we reflect multiple dimensions, since this will not be the last time that a dimension is added. 
We already have 2.

**Comment by oliversauter** [comment]
also I will change the domain_list into `sources` then in the table architecture to reflect the implementation.

**Comment by hoshomoh** [comment]
Cool. I would keep updating them if there are any changes.

**Comment by oliversauter** [comment]
So how do we resolve this with the states? we definitely need to be able to see the progress of indexing and that it is a trusted source separately. I would suggest the `trusted` state could just be a column in the table now?

**Comment by hoshomoh** [comment]
Yeah. That is already a separate field  ```trusted_source```. Can either be ```True``` or ```False```

**Comment by oliversauter** [comment]
Ok. So resolution:

- adding of last time crawled
- adding of errormessage for domains in case of `FAILED`

Do we also need these states for the URLs in `all_urls` table?

I could imagine `PARSED` `FAILED` `INDEXED` as suitable states?

**Comment by hoshomoh** [comment]
There is a ```state``` field in ```all_urls``` table which supports two states at the moment ```PENDING``` and ```PROCESSED```

**Comment by oliversauter** [comment]
ok, then lets add `FAILED` and `INDEXED` (processed via elastic search)  to it.  Would it make sense to change `PROCESSED` into `PARSED`(processed via content_extractor)?

**Comment by oliversauter** [comment]
actually that was more of a question as a command. What do you think about the addition?

**Comment by hoshomoh** [comment]
@oliversauter write all the changes we talked about in a separate issue and assign it to me. Would work on it with #41. If it make sense, you can actually update #41 instead.

**Comment by oliversauter** [comment]
yeah then i update 41 with that. Thanks!

**Comment by oliversauter** [comment]
@hoshomoh 
is that already done? Its the task we talked about in the call. so this API endpoint exists now? 
It's existence is important for https://github.com/WorldBrain/webmarks/issues/29#issuecomment-252726225

**Comment by hoshomoh** [comment]
Yeah this is done.
