### ISSUE TITLE
Module: Spider

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#41]
## Goal:

Making a list of all URLs for a given domain

## Input

Gets domain from Django app

## Output

1. Gives a list of URLs to Django app, which saves it to table `all_urls` in our PostgreSQL DB. 
Format:
 - `url`=URL
 - `domain_name`=Domainname in format "subdomain.domain.com" (subdomain if applicable)
 - `processed_article_detector`=`false`
 - `is_article`=`false`
2. Sets the column `processed_linkchecker`=`timestamp` in table `domain_list`. 
In case of error, `processed_linkchecker`=failed +`timestamp`

## Technical Implementation

Scrapy has to be able to run multithreaded with django.

Options:
1. Using ScrapingHub "Scrapy Cloud Unit". (http://scrapinghub.com/pricing/)
2. Using our own scrapy crawler

Important, configure the scraper to ignore all urls with "?" in it (querystrings) and more than 200 characters (possibility for loop)

## Important to clarify

**1.** Scrapy has a free tier, where we can have 1 concurrent crawl at a time. If we use scrapinghub we should be able to upgrade to more concurrent crawls without changing code on our side. 
The idea is to implement a buffer, that just has a wait list of domains to be crawled. If we upgrade to to 2-3 concurrent crawls, it should just take 2-3 out of the wait list.

In order to make more concurrent runs, we could take as a standard our own scrapy instance, running on our servers and as soon as we get banned redirect the domain to make the crawl with scrapinghub's scrapy cloud unit. 
Also by letting scrapinghub run on the sideline all the time with the free tier, we can already scrape quite some pages. 

**2.** Can we use scrapinghub with Django more easily?

**Comment by lwm** [comment]
Closing due to project reset.

**Comment by oliversauter** [comment]
Wait wait :) this is the part that Vasile is building. There has been no change to that. It is part of the pipeline I drew in https://github.com/WorldBrain/project-management/issues/24.

The linkchecker is basically scrapy multithreaded. 

If you read the issue 24 in project-management and follow the steps of the crawler to understand what I mean.

**Comment by lwm** [comment]
For sure vasile can read the guides here, but these aren't relevant to cortex any more and I am cleaning up. When a new repo for the crawler arrives, we open it there?

**Comment by lwm** [comment]
I 100% knew you would open every single one of these again ...
