### ISSUE TITLE
Module: article_detector_stage1

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#42]
## Goal:

Detect, which URL that has been generated by the module `linkchecker` is likely to be an article. 
We do so because we don't want to waste parsing units (because we pay for them) 

## Input

List of URLs coming from the django app, which has them from the table `all_urls` where column `processed`=`False`

## Output

 - Gives a list of URLs to Django app, which saves it to table `articles` in our PostgreSQL DB.
 - Sets `is_article`= `true` in table `all_urls` for URLs that have been identified as article
 
## Technical Implementation

 - Needs to throw out all URLs that have certain strings in it (ie. "/category/" , "/tag" , ".jpg" etc.)
 - Needs to take expandable list of strings, so we can adapt better

**Comment by lwm** [comment]
Closing due to project reset.
