### ISSUE TITLE
Module: HTML_Parser

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#43]
## Goal:

Parsing the HTML code of every URL that has been identified as an article

## Input

Gets URL from django app from table `articles` where column `processed_html_parser`=`false``

## Output

- Gives a JSON file to django app with fields `url` and `html`, which saves `html`,  `processed_html_parser`=`timestamp` to table `articles`, where `url` = URL

## Technical Implementation

Here we can use newspaper3k or boilerpipe to parse the HTML code of a URL. 
As soon as we get banned by the domain, we route the URLs of that specific domain to *[Crawlera](http://scrapinghub.com/crawlera/)*

This way we avoid unnecessarily consuming the requests we can have at Crawlera. For most blogs and websites it should work just fine with our own crawlers.

**Comment by lwm** [comment]
Closing due to project reset.
