### ISSUE TITLE
Module: content_extractor

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#44]
## Goal:

Extracting the important content bits from the HTML code we saved for each article URL

## Input

Gets the HTML file for each URL in table `articles` where column `processed_content_extractor`=`false` from django app

## Output

Gives back a JSON file containing
 -  `domain_name`, 
 - `url`,
 -  `text`,
 -  `keywords`(list),
 -  `authors`(list),
 -  `publish_date`, 
 - `tags`(list), 
 - `summary`,
 -  `links`(list)
 - `parse_time``

 to the django app, which saves it to the respective columns in table `articles`.

## Technical Implementation

I think you guys already have built the extractor we can use to parse the elements out of the HTML file, right? @lwm @arsenal9971

**Comment by lwm** [comment]
Closing due to project reset.
