### ISSUE TITLE
Dockerize cortex

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#6]
As a first step towards a repeatably deployable architecture, we need to deploy cortex, the django app, in a docker container. This would involve quite a bit of work, namely:

  - [ ] integrating uWSGI as a web server and exposing the API
  - [ ] creating a seperate PostgreSQL container to link to
  - [ ] creating a seperate ES container to link to

It might be worth to start with `docker-compose` from the beginning. Othwerwise, arrange them by hand, then use the `Makefile` to abstract the commands and let the configuration management take care of linking them.

Lots of open questions.

**Comment by oliversauter** [comment]
Tasks needed to have this done:

- [ ]  #24 
- [ ]  #25 
- [ ]  #28 
- [ ]  #29

**Comment by amitkumarj441** [comment]
@oliversauter I just added a Dockerfile for PostgreSQL #24

**Comment by amitkumarj441** [comment]
@oliversauter There should be some prerequisites for integrating uWSGI as a web server: i.e., uWSGI Container and then we create our docker-compose file to deploy cortex.
