### ISSUE TITLE
receive crawl job JSON end point

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/cortex#8]
Following from #48.

Once a crawl has finished its work, it will need to send it's scraped content back to `cortex`.

We need an end point that looks like:

```
POST /api/articles/
```

Which accepts an a JSON body of an `Article` and saves it to the database.

Please see https://github.com/WorldBrain/project-management/issues/25 for structure of an article.

**Comment by oliversauter** [comment]
done @hoshomoh @tobisanya

**Comment by hoshomoh** [comment]
I am not sure about this. But I think @tobisanya worked on this.

**Comment by vpolisky** [comment]
Actually, I think, that there is no need of this. Articles and URLs are directly saved into the database by crawler.
